### ISSUE TITLE
No route matches [GET] "/blocks/edit_overview"

### ISSUE THREAD

**Issue by arquio** [tastapod/redmine_blocks_layout#19]
Hello!!
First Thanks u for your plugin...

Do you know how can I fix this problem?

Thank u!

> Started GET "/blocks/edit_overview?project_id=ticketing" for 213.98.48.239 at 2016-08-19 16:58:04 +0200
> 
> ActionController::RoutingError (No route matches [GET] "/blocks/edit_overview"):
>   actionpack (3.2.19) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
>   actionpack (3.2.19) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
>   railties (3.2.19) lib/rails/rack/logger.rb:32:in `call_app'
>   railties (3.2.19) lib/rails/rack/logger.rb:16:in`block in call'
>   activesupport (3.2.19) lib/active_support/tagged_logging.rb:22:in `tagged'
>   railties (3.2.19) lib/rails/rack/logger.rb:16:in`call'
>   actionpack (3.2.19) lib/action_dispatch/middleware/request_id.rb:22:in `call'
>   rack (1.4.7) lib/rack/methodoverride.rb:21:in`call'
>   rack (1.4.7) lib/rack/runtime.rb:17:in `call'
>   activesupport (3.2.19) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
>   rack (1.4.7) lib/rack/lock.rb:15:in `call'
>   actionpack (3.2.19) lib/action_dispatch/middleware/static.rb:63:in`call'
>   rack-cache (1.6.1) lib/rack/cache/context.rb:140:in `forward'
>   rack-cache (1.6.1) lib/rack/cache/context.rb:249:in`fetch'
>   rack-cache (1.6.1) lib/rack/cache/context.rb:189:in `lookup'
>   rack-cache (1.6.1) lib/rack/cache/context.rb:66:in`call!'
>   rack-cache (1.6.1) lib/rack/cache/context.rb:51:in `call'
>   railties (3.2.19) lib/rails/engine.rb:484:in`call'
>   railties (3.2.19) lib/rails/application.rb:231:in `call'
>   rack (1.4.7) lib/rack/content_length.rb:14:in`call'
>   railties (3.2.19) lib/rails/rack/log_tailer.rb:17:in `call'
>   rack (1.4.7) lib/rack/handler/webrick.rb:59:in`service'
>   /usr/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
>   /usr/lib/ruby/2.1.0/webrick/httpserver.rb:94:in`run'
>   /usr/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

[redmine_error-log.txt](https://github.com/tastapod/redmine_blocks_layout/files/427277/redmine_error-log.txt)

**Comment by tastapod** [comment]
Hi Daniel,

I’m not actively maintaining this plugin any more. It looks like the route
has been changed in a later version of Redmine so that /blocks/edit_overview is
no longer a valid route. If you want to submit a pull request for a fix I
am happy to merge it for you.

On 19 August 2016 at 16:14:29, Daniel Calle Rosa (notifications@github.com)
wrote:

Hello!!
First Thanks u for your plugin...

Do you know how can I fix this problem?

Thank u!

Started GET "/blocks/edit_overview?project_id=ticketing" for 213.98.48.239
at 2016-08-19 16:58:04 +0200

ActionController::RoutingError (No route matches [GET]
"/blocks/edit_overview"):
actionpack (3.2.19)
lib/action_dispatch/middleware/debug_exceptions.rb:21:in call'
actionpack (3.2.19) lib/action_dispatch/middleware/show_exceptions.rb:56:in
call'
railties (3.2.19) lib/rails/rack/logger.rb:32:in call_app'
railties (3.2.19) lib/rails/rack/logger.rb:16:inblock in call'
activesupport (3.2.19) lib/active_support/tagged_logging.rb:22:in tagged'
railties (3.2.19) lib/rails/rack/logger.rb:16:incall'
actionpack (3.2.19) lib/action_dispatch/middleware/request_id.rb:22:in call'
rack (1.4.7) lib/rack/methodoverride.rb:21:incall'
rack (1.4.7) lib/rack/runtime.rb:17:in call'
activesupport (3.2.19)
lib/active_support/cache/strategy/local_cache.rb:72:incall'
rack (1.4.7) lib/rack/lock.rb:15:in call'
actionpack (3.2.19) lib/action_dispatch/middleware/static.rb:63:incall'
rack-cache (1.6.1) lib/rack/cache/context.rb:140:in forward'
rack-cache (1.6.1) lib/rack/cache/context.rb:249:infetch'
rack-cache (1.6.1) lib/rack/cache/context.rb:189:in lookup'
rack-cache (1.6.1) lib/rack/cache/context.rb:66:incall!'
rack-cache (1.6.1) lib/rack/cache/context.rb:51:in call'
railties (3.2.19) lib/rails/engine.rb:484:incall'
railties (3.2.19) lib/rails/application.rb:231:in call'
rack (1.4.7) lib/rack/content_length.rb:14:incall'
railties (3.2.19) lib/rails/rack/log_tailer.rb:17:in call'
rack (1.4.7) lib/rack/handler/webrick.rb:59:inservice'
/usr/lib/ruby/2.1.0/webrick/httpserver.rb:138:in service'
/usr/lib/ruby/2.1.0/webrick/httpserver.rb:94:inrun'
/usr/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

redmine_error-log.txt
<https://github.com/tastapod/redmine_blocks_layout/files/427277/redmine_error-log.txt>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tastapod/redmine_blocks_layout/issues/19>, or mute the
thread

**Comment by arquio** [comment]
Thanks for all.I will say to the new company redmine mantainer.
